name: Update minimal gist

on:
  push:
    branches:
      - main
    paths:
      - minimal/index.ts
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.gist.outputs.url }}
    steps:
      - uses: actions/checkout@v5
      - name: Update gist from file
        id: gist
        uses: xSAVIKx/gist-uploader-action@v0.1.3       # pin to a released version
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 78eaeb461417f265fda71771cf8bb872     # ID of the target gist
          file_path: minimal/index.ts  # path in your repo to upload
          gist_description: "GCP Cloud Workstations minimal setup with Pulumi, Typescript and Bun"
